# Generated by Django 4.2.3 on 2023-08-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="product",
            field=models.ManyToManyField(
                related_name="parameters",
                through="goods.ProductParameter",
                to="goods.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="parameter",
            field=models.ManyToManyField(
                related_name="products",
                through="goods.ProductParameter",
                to="goods.parameter",
            ),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="parameter_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_parameters",
                to="goods.parameter",
            ),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_parameters",
                to="goods.product",
            ),
        ),
    ]
