# Generated by Django 4.2.3 on 2023-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_parameter_product_alter_product_parameter_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="product",
            name="price_with_delivery",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
