# Generated by Django 4.2.3 on 2023-08-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_product_distributor_alter_distributor_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
